services:
    db:
        image: postgres:12
        environment:
            - POSTGRES_DB=snippetsly-db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./src:/app/src
        ports:
            - '8080:8080'
        depends_on:
            - db
        environment:
            - POSTGRES_DB=snippetsly-db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_HOST=db
